version: "3.9"
services:
  order_api:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_PUBLIC_KEY: ${STRIPE_PUBLIC_KEY}
      STRIPE_WEBHOOK: ${STRIPE_WEBHOOK}
    networks:
      - api_user
    depends_on:
      - basedatos
    restart: always

  basedatos:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ApiUser$123
      MYSQL_DATABASE: order_db
      MYSQL_USER: api_user
      MYSQL_PASSWORD: ApiUser$123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - api_user

networks:
  api_user:

volumes:
  db_data: